//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorForm.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/add", ReplyAction="http://tempuri.org/ICalculator/addResponse")]
        double add(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/add", ReplyAction="http://tempuri.org/ICalculator/addResponse")]
        System.Threading.Tasks.Task<double> addAsync(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/subtract", ReplyAction="http://tempuri.org/ICalculator/subtractResponse")]
        double subtract(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/subtract", ReplyAction="http://tempuri.org/ICalculator/subtractResponse")]
        System.Threading.Tasks.Task<double> subtractAsync(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/multiply", ReplyAction="http://tempuri.org/ICalculator/multiplyResponse")]
        double multiply(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/multiply", ReplyAction="http://tempuri.org/ICalculator/multiplyResponse")]
        System.Threading.Tasks.Task<double> multiplyAsync(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/divide", ReplyAction="http://tempuri.org/ICalculator/divideResponse")]
        double divide(double no1, double no2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/divide", ReplyAction="http://tempuri.org/ICalculator/divideResponse")]
        System.Threading.Tasks.Task<double> divideAsync(double no1, double no2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : CalculatorForm.ServiceReference.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<CalculatorForm.ServiceReference.ICalculator>, CalculatorForm.ServiceReference.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(double no1, double no2) {
            return base.Channel.add(no1, no2);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(double no1, double no2) {
            return base.Channel.addAsync(no1, no2);
        }
        
        public double subtract(double no1, double no2) {
            return base.Channel.subtract(no1, no2);
        }
        
        public System.Threading.Tasks.Task<double> subtractAsync(double no1, double no2) {
            return base.Channel.subtractAsync(no1, no2);
        }
        
        public double multiply(double no1, double no2) {
            return base.Channel.multiply(no1, no2);
        }
        
        public System.Threading.Tasks.Task<double> multiplyAsync(double no1, double no2) {
            return base.Channel.multiplyAsync(no1, no2);
        }
        
        public double divide(double no1, double no2) {
            return base.Channel.divide(no1, no2);
        }
        
        public System.Threading.Tasks.Task<double> divideAsync(double no1, double no2) {
            return base.Channel.divideAsync(no1, no2);
        }
    }
}
